### ISSUE TITLE
ImportError: cannot import name 'sd_unet' from 'modules' (unknown location)

### ISSUE THREAD

**Issue by Cubey42** [AUTOMATIC1111/stable-diffusion-webui-tensorrt#2]
Error loading script: trt.py
Traceback (most recent call last):
  File "H:\NovelAI\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "H:\NovelAI\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\NovelAI\stable-diffusion-webui\extensions\stable-diffusion-webui-tensorrt\scripts\trt.py", line 6, in <module>
    from modules import script_callbacks, sd_unet, devices, shared, paths_internal
ImportError: cannot import name 'sd_unet' from 'modules' (unknown location)

**Comment by kilkal-kol** [comment]
Had the same issue. Fixed by using dev branch.
"Adds the ability to convert loaded model's Unet module into TensortRT. Requires version least after commit 339b5315 (currently, it's the dev branch after 2023-05-27). Only tested to work on Windows."

**Comment by Cubey42** [comment]
thank you.

**Comment by Qxzz2** [comment]
> Had the same issue. Fixed by using dev branch. "Adds the ability to convert loaded model's Unet module into TensortRT. Requires version least after commit 339b5315 (currently, it's the dev branch after 2023-05-27). Only tested to work on Windows."

Any chance you could elaborate on how to go about implementing this? Also having this issue, but can't resolve.

**Comment by hiyata** [comment]
Just went through this, open up cmd in your stable-diffusion-webui folder and type "git checkout dev". Then type "webui-user.bat" and you should be able to follow the instructions. Make sure the TensorRT folder is being used, the one inside TensorRT-8.6.1.6..etc.
