### ISSUE TITLE
tensorrt-8.6.1-cp310-none-linux_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by yuvraj108c** [AUTOMATIC1111/stable-diffusion-webui-tensorrt#39]
Followed all instructions carefully & getting this error while starting webui. Im using ubuntu 20, with cuda 12.1

`*** Error running install.py for extension /home/ubuntu/stable-diffusion-webui/extensions/stable-diffusion-webui-tensorrt.
*** Command: "/home/ubuntu/stable-diffusion-webui/venv/bin/python3" "/home/ubuntu/stable-diffusion-webui/extensions/stable-diffusion-webui-tensorrt/install.py"
*** Error code: 1
*** stdout: Installing TensorRT wheel
***
*** stderr: Traceback (most recent call last):
***   File "/home/ubuntu/stable-diffusion-webui/extensions/stable-diffusion-webui-tensorrt/install.py", line 30, in <module>
***     install()
***   File "/home/ubuntu/stable-diffusion-webui/extensions/stable-diffusion-webui-tensorrt/install.py", line 20, in install
***     launch.run_pip(f'install "{whl}"', "TensorRT wheel")
***   File "/home/ubuntu/stable-diffusion-webui/modules/launch_utils.py", line 130, in run_pip
***     return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
***   File "/home/ubuntu/stable-diffusion-webui/modules/launch_utils.py", line 107, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install TensorRT wheel.
*** Command: "/home/ubuntu/stable-diffusion-webui/venv/bin/python3" -m pip install "/home/ubuntu/stable-diffusion-webui/extensions/stable-diffusion-webui-tensorrt/TensorRT-8.6.1.6/python/tensorrt-8.6.1-cp310-none-linux_x86_64.whl" --prefer-binary
*** Error code: 1
*** stderr: ERROR: tensorrt-8.6.1-cp310-none-linux_x86_64.whl is not a supported wheel on this platform.`

**Comment by Roop-AI** [comment]
did you find a solution or just gave up?
